name: Build & Deploy Static HTML to Render

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🧪 Run basic test (check index.html exists)
      run: |
        if [ ! -f index.html ]; then
          echo "index.html not found!"
          exit 1
        fi
        echo "index.html found, test passed!"

    - name: 🚀 Deploy to Render using Deploy Hook
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
