name: CI for Static Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    name: HTML Linter Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: |
          npm install -g htmlhint

      - name: Lint HTML files
        run: |
          htmlhint index.html
